# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Slater Stich
tagline:          
url:              http://www.slaterstich.com
baseurl:          /ab_testing_statistics/
author:
  name:           Slater
  url:            https://www.slaterstich.com
  email:          slater.stich@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:          https://github.com/
link_beta:      /use_the_beta_distribution/
link_hier:      use_a_hierarchical_model
link_biased:    avoid_biased_stopping_times
link_retest:    retest_and_watch_the_base_rate

